/**
 * Precomputed AI hero scores — generated offline for all state×device combos.
 *
 * AUTO-GENERATED by scripts/generate-ai-scores.ts
 * Run: npm run generate-scores
 *
 * Regenerate whenever content library changes (headlines, descriptions, ctas, proofs).
 * Cache key format: "{intent}_{trust}_{energy}_{deviceType}"
 */

export interface PrecomputedSlotScore {
  id: string;
  score: number;
  reason?: string;
}

/** Shape matches RawHeroAIResponse so parseHeroAIResponse() works directly on this. */
export interface PrecomputedHeroScores {
  headline_scores: PrecomputedSlotScore[];
  description_scores: PrecomputedSlotScore[];
  cta_scores: PrecomputedSlotScore[];
  proof_scores: PrecomputedSlotScore[];
  model: string;
  latency_ms: number;
}

/** SHA-256 of concatenated content source files at generation time. */
export const CONTENT_HASH = "0266735d2bf470b0";

/** ISO timestamp of last generation. */
export const GENERATED_AT = "2026-04-04T07:17:09.115Z";

/**
 * Lookup table: cache_key → precomputed hero scores (pre-guardrail).
 * Guardrails are still applied at runtime (instantaneous, no cost).
 */
export const AI_SCORE_CACHE: Record<string, PrecomputedHeroScores> = {
  "exploring_low_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.700 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.300 }, { id: "proof_kpi_a", score: 0.600 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 11554,
  },

  "exploring_low_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.300 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10802,
  },

  "exploring_low_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.300 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 12390,
  },

  "exploring_low_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.300 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 8342,
  },

  "exploring_low_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.600 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 8868,
  },

  "exploring_low_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.600 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 9942,
  },

  "exploring_medium_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.700 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 9851,
  },

  "exploring_medium_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.700 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.500 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.100 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 9303,
  },

  "exploring_medium_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.700 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.500 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 12494,
  },

  "exploring_medium_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 11677,
  },

  "exploring_medium_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.600 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.600 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 10038,
  },

  "exploring_medium_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10068,
  },

  "exploring_high_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.800 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.700 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 8776,
  },

  "exploring_high_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.800 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.700 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 8403,
  },

  "exploring_high_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7888,
  },

  "exploring_high_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.400 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10551,
  },

  "exploring_high_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 7885,
  },

  "exploring_high_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.800 }, { id: "headline_action_a", score: 0.650 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.650 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.550 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.750 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10548,
  },

  "evaluating_low_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10144,
  },

  "evaluating_low_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.700 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.600 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 6861,
  },

  "evaluating_low_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.700 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.300 }, { id: "proof_kpi_a", score: 0.600 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.700 }],
    model: "gpt-4o-mini",
    latency_ms: 9977,
  },

  "evaluating_low_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.200 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7440,
  },

  "evaluating_low_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.600 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.200 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 8770,
  },

  "evaluating_low_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10631,
  },

  "evaluating_medium_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.400 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.200 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 8257,
  },

  "evaluating_medium_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 9018,
  },

  "evaluating_medium_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 10033,
  },

  "evaluating_medium_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.500 }, { id: "headline_authority_b", score: 0.600 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.500 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 7993,
  },

  "evaluating_medium_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7944,
  },

  "evaluating_medium_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.500 }, { id: "headline_authority_b", score: 0.600 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 8492,
  },

  "evaluating_high_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.500 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 8362,
  },

  "evaluating_high_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 7448,
  },

  "evaluating_high_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 8524,
  },

  "evaluating_high_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.650 }, { id: "headline_authority_b", score: 0.750 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.550 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.850 }],
    model: "gpt-4o-mini",
    latency_ms: 7859,
  },

  "evaluating_high_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.800 }, { id: "headline_action_a", score: 0.650 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.650 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.750 }, { id: "proof_none", score: 0.200 }, { id: "proof_showreel_kpi_a", score: 0.850 }],
    model: "gpt-4o-mini",
    latency_ms: 8235,
  },

  "evaluating_high_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 7297,
  },

  "ready_low_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 9483,
  },

  "ready_low_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 6674,
  },

  "ready_low_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 8602,
  },

  "ready_low_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.600 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7994,
  },

  "ready_low_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.600 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7887,
  },

  "ready_low_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.300 }, { id: "headline_authority_b", score: 0.400 }, { id: "headline_action_a", score: 0.600 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.500 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7505,
  },

  "ready_medium_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.500 }, { id: "desc_medium_b", score: 0.600 }, { id: "desc_short_a", score: 0.400 }, { id: "desc_short_b", score: 0.500 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7887,
  },

  "ready_medium_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.400 }, { id: "headline_authority_b", score: 0.500 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.500 }, { id: "cta_soft_a", score: 0.400 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.700 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.800 }],
    model: "gpt-4o-mini",
    latency_ms: 7455,
  },

  "ready_medium_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.400 }, { id: "headline_problem_b", score: 0.500 }, { id: "headline_authority_a", score: 0.600 }, { id: "headline_authority_b", score: 0.700 }, { id: "headline_action_a", score: 0.500 }],
    description_scores: [{ id: "desc_medium_a", score: 0.600 }, { id: "desc_medium_b", score: 0.700 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.800 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.600 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 6866,
  },

  "ready_medium_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.500 }, { id: "headline_authority_b", score: 0.600 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.500 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 8812,
  },

  "ready_medium_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.500 }, { id: "headline_authority_b", score: 0.600 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.500 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 9591,
  },

  "ready_medium_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.500 }, { id: "headline_authority_b", score: 0.600 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.500 }, { id: "desc_short_b", score: 0.600 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.500 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.400 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 9264,
  },

  "ready_high_low_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.500 }, { id: "headline_problem_b", score: 0.600 }, { id: "headline_authority_a", score: 0.700 }, { id: "headline_authority_b", score: 0.800 }, { id: "headline_action_a", score: 0.700 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.700 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.600 }, { id: "cta_soft_a", score: 0.500 }, { id: "cta_diagnostic_a", score: 0.700 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 8598,
  },

  "ready_high_low_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.800 }, { id: "headline_authority_b", score: 0.750 }, { id: "headline_action_a", score: 0.650 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.650 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.850 }],
    model: "gpt-4o-mini",
    latency_ms: 7279,
  },

  "ready_high_low_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.650 }, { id: "headline_authority_b", score: 0.750 }, { id: "headline_action_a", score: 0.800 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.850 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.650 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.700 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.850 }],
    model: "gpt-4o-mini",
    latency_ms: 5222,
  },

  "ready_high_high_desktop": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.800 }, { id: "headline_authority_b", score: 0.750 }, { id: "headline_action_a", score: 0.650 }],
    description_scores: [{ id: "desc_medium_a", score: 0.750 }, { id: "desc_medium_b", score: 0.800 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.650 }, { id: "cta_diagnostic_a", score: 0.750 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.850 }, { id: "proof_argument_a", score: 0.800 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.900 }],
    model: "gpt-4o-mini",
    latency_ms: 7991,
  },

  "ready_high_high_mobile": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.750 }, { id: "headline_authority_b", score: 0.800 }, { id: "headline_action_a", score: 0.650 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.850 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.600 }, { id: "cta_diagnostic_a", score: 0.650 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.750 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.850 }],
    model: "gpt-4o-mini",
    latency_ms: 5643,
  },

  "ready_high_high_tablet": {
    headline_scores: [{ id: "headline_problem_a", score: 0.600 }, { id: "headline_problem_b", score: 0.700 }, { id: "headline_authority_a", score: 0.800 }, { id: "headline_authority_b", score: 0.750 }, { id: "headline_action_a", score: 0.650 }],
    description_scores: [{ id: "desc_medium_a", score: 0.700 }, { id: "desc_medium_b", score: 0.750 }, { id: "desc_short_a", score: 0.600 }, { id: "desc_short_b", score: 0.650 }],
    cta_scores: [{ id: "cta_direct_a", score: 0.900 }, { id: "cta_guided_a", score: 0.700 }, { id: "cta_soft_a", score: 0.650 }, { id: "cta_diagnostic_a", score: 0.600 }],
    proof_scores: [{ id: "proof_showreel_a", score: 0.500 }, { id: "proof_kpi_a", score: 0.800 }, { id: "proof_argument_a", score: 0.750 }, { id: "proof_none", score: 0.000 }, { id: "proof_showreel_kpi_a", score: 0.850 }],
    model: "gpt-4o-mini",
    latency_ms: 6448,
  },
};
